# Generated by Django 4.0.2 on 2022-08-01 10:13

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='visibility',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private')], default='public', max_length=7),
        ),
    ]
