# Generated by Django 4.0.2 on 2022-08-03 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_alter_question_question_text_alter_quiz_visibility'),
        ('Participate', '0002_clarification'),
    ]

    operations = [
        migrations.AddField(
            model_name='clarification',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Quiz.quiz'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='clarification',
            index=models.Index(fields=['quiz', 'question'], name='Participate_quiz_id_a9610c_idx'),
        ),
    ]
