# Generated by Django 4.0.2 on 2022-08-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Participate', '0003_clarification_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clarification',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
    ]
